KevinBatdorf/code-block-pro

- readme.txt
- src/front/style.css
This PR sets margins to 0 on pre tags to avoid inheriting it from the user agent.
> Override margins on pre tags

- cypress/support/commands.js
- readme.txt
- src/block.json
- src/editor/editor.css
- src/front/style.css
- src/index.tsx
This fixes a scenario where some themes will force alignment within the editor
> Fix text alignment issues

- readme.txt
- src/block.json
- src/front/style.css
- src/index.tsx
A user reported some style issues with [the Hueman theme](https://wordpress.org/themes/hueman/). This PR attempts to override those and generally overrides common scenarios other themes may be using to override
> Add hueman styling support

- code-block-pro.php
- compatibility.php
- readme.txt
Prismatic: https://wordpress.org/plugins/prismatic/
This plugin encodes all `<code>` tags in the content, resulting in escaped html.
https://plugins.trac.wordpress.org/browser/prismatic/trunk/inc/prismatic-core.php#L59
I'll monitor that plugin periodically and remove this override if it is updated.
With Prismatic active:
Original:
> Add prismatic compatibility overrides

- readme.txt
- src/block.json
- src/editor/controls/Sidebar.tsx
- src/front/BlockOutput.tsx
- src/index.tsx
- src/state/theme.ts
- src/types.ts
- src/util/fonts.ts
This PR will clamp values. Useful especially on old Bootstrap themes where the font size is showing 10px on the html tag
> Add clamp option to font sizing

- src/editor/components/HeaderSelect.tsx
- src/editor/controls/Sidebar.tsx
- src/editor/editor.css
- src/front/style.css
This just lowers the opacity for better readability on most themes (some were ok previously). Was a bit hesitant to make a front facing color change like this but I think having the line numbers more accessible should be the default, and users can choose to override the styling to customize outside of that.
> Improve line number readability

- .github/workflows/cypress.yml
- .wp-env.json
- code-block-pro.php
- cypress/e2e/compatability.cy.js
- cypress/e2e/language.cy.js
- cypress/e2e/themes.cy.js
- cypress/support/globals.js
- php/compatibility.php
- readme.txt
This fixes an issue with prismatic. Unfortunately I need to disable their plugin in order to function as they indiscriminately filter all code tags. I do this in a way that is not destructive in case the user later deletes this plugin. However, if they add a new method, I need to override that one too.
This PR will override a new method they added, and also includes a test to check daily for fatal errors via GitHu, using cypress
more context: https://wordpress.org/support/topic/enabling-plugin-with-prismatic-gives-error/
> Add compatibility fix and test for prismatic

- code-block-pro.php
- readme.txt
- Fix: Adjusted editor padding for line numbers to better match the front end
- Fix: Removed the TW border default in the editor as it was overriding soem wp defaults
- Fix: Updated a typo on the word "focus"
- Testing: Adds coverage for every main feature.
> Release 1.9.3

- readme.txt
- src/editor/components/FooterSelect.tsx
- src/editor/components/footers/SimpleStringStart.tsx
- src/editor/controls/Sidebar.tsx
This adds a footer option to align next on the left. Notice the text here:
It essentially copies the right-side footer text option but places the text at 16px from the left vs 10px on the right
> Add footer text start

- readme.txt
- src/front/front.js
This will load the front end scripts (highlighting, copy button, font loading) immediately, during `DOMContentLoaded`, and `load` so that no matter where the user (more likely a plugin) loads the script it should run.
Tested this using Autoptimize and various configurations
> Add smarter load listener

- readme.txt
- src/editor/editor.css
Latest Gutenberg plugin adds a blue outline on inner textarea elements when focused. This doesn't work for us since it's acting like a code editor.
> Remove outline from block

- .eslintrc
- .github/workflows/build-production-zip.yml
- .github/workflows/cypress.yml
- .github/workflows/release-to-wp-org.yml
- cypress/e2e/styling.cy.js
- package-lock.json
- package.json
- readme.txt
- src/editor/components/FontSelect.tsx
- src/front/style.css
- src/index.tsx
This fixes a bug where in the editor the font ligatures would cause a mismatch on line width and the cursor placement would get wonky. A textarea can't render font ligs so no choice really but to disable that in the editor. 
closes https://github.com/KevinBatdorf/code-block-pro/issues/109
> Fix line wrap editor bug

- .github/workflows/cypress.yml
- cypress/e2e/footers.cy.js
- cypress/e2e/themes.cy.js
- cypress/support/gutenberg.js
- src/editor/controls/Toolbar.tsx
This tweaks the tests to test for RC WP versions instead of the main branch. 
TODO: I wonder if I can fetch the latest tag first within the GH action and use that rather than hard code the branch
> Update failing tests

- .github/workflows/cypress.yml
This should run each spec in isolation so random failures unrelated to the PR can be re-run more quickly
> Break up cypress workflow jobs

- src/editor/components/HeightPanel.tsx
- src/editor/components/SeeMoreSelect.tsx
This updates the max height sidebar ui a bit. it's still not super intuitive but I think it's more clear now than what's released.
The issue is that the user may want the front end at a max height, but the editor fully expanded so they can edit the code. Or vice versa where they have long code that needs to display in full on the front end but truncated on the back. 
This may be a case of over thinking it though!
> Update max height sidebar ui

- .github/workflows/cypress-main.yml
- .github/workflows/cypress-push.yml
`continue-on-error` will ignore failures completely, while `fail-fast: false` will not stop other runs, but will fail the job globally (and more importantly, email + show the red check on the PR)
> Disable workflow fail fast

- src/defaultLanguages.json
- src/hooks/useTheme.ts
- src/types.ts
This adds a plaintext option, which essentially just doesn't use any language
closes #162
> Add plaintext option

- .github/workflows/cypress-main.yml
- .github/workflows/cypress-push.yml
- code-block-pro.php
- cypress/e2e/lines.cy.js
- cypress/e2e/permissions.cy.js
- cypress/support/commands.js
- cypress/support/navigate-pages.js
- cypress/support/wp-cli.js
- readme.txt
- src/editor/Edit.tsx
- src/editor/components/misc/MissingPermissions.tsx
- src/editor/controls/Sidebar.tsx
- src/index.tsx
- src/types.ts
This adds a notice to users who have permission to edit a page but not `unfiltered_html` permission. It also blocks access to updating attributes (although it's easily enough to bypass - the db blocks dangerous html regardless).
The issue is mainly SVGs though
closes https://github.com/KevinBatdorf/code-block-pro/issues/165
> Add no permissions notice

- README.md
- package-lock.json
- package.json
- src/editor/Edit.tsx
- src/editor/components/HeaderSelect.tsx
- src/editor/components/ThemeFilter.tsx
- src/editor/components/ThemePreview.tsx
- src/editor/components/ThemeSelect.tsx
- src/editor/components/footers/SimpleStringEnd.tsx
- src/editor/components/footers/SimpleStringStart.tsx
- src/editor/components/headers/Headlights.tsx
- src/editor/components/headers/HeadlightsMuted.tsx
- src/editor/components/headers/SimpleString.tsx
- src/editor/components/misc/Unsupported.tsx
- src/editor/controls/Toolbar.tsx
- src/front/BlockOutput.tsx
- src/hooks/useTheme.ts
- src/index.tsx
- src/types.ts
- src/util/colors.ts
- src/util/themes.ts
This PR adds support for custom styles. You can add your own via a filter or otherwise buy the [theme pack](https://code-block-pro.com/themes).
This opens up using css variables for light/dark mode, etc. See here: https://github.com/KevinBatdorf/code-block-pro/discussions/168
> Add custom theme support

- readme.txt
- src/defaultLanguages.json
- src/editor/controls/Sidebar.tsx
- src/util/languages.ts
This fixes a few issues with the language selection:
- wolfram typo
- removes the filtering of bash and zsh filtering
- Sorts the list by label rather than key
> Fix Wolfram language bug

- code-block-pro.php
- readme.txt
- Tweak: Removes the filtering of bash and zsh filtering
- Fix: Better language sorting (by label instead of key)
- Fix: Fix typo in Wolfram language key
> Release 1.16.1

- readme.txt
- src/editor/Edit.tsx
This PR simply adds autofocus to the `<Editor/>` when the Code Pro block has been added to the block editor.
If the code block has `code` autofocus is set to `false` as it assumes the block hasn't been just added to the block editor.
The use-case for this is that I frequently:
1. Copy code from another source.
2. Open WordPress, and add Code Pro block.
3. `Cmd + V` but nothing happens because the focus is not on the editor :)
This PR solves the above by auto-focusing after the block has been added.
> Autofocus on Editor

- code-block-pro.php
- readme.txt
- src/editor/controls/Sidebar.tsx
- Feature: Add Fantasque Sans Mono (https://github.com/belluzj/fantasque-sans)
- Feature: Add Comic Mono font (https://github.com/dtinth/comic-mono-font)
- Tweak: Default to Jetbrains Mono font
- Tweak: Remove line highlights on hover when blurred
- Tweak: Add minor adjustments for fonts to normalize line heights
- Fix: Block will be auto-focused on insert - WP6.2 regression
- Fix: Line highlight hover width was not rendering correctly
- Fix: Line highlighter will find the longest line to use as the highlighter width
> Release 1.19.0

- readme.txt
- src/editor/editor.css
This fixes a bug where an empty span rendered (only on some languages, and not sure why it renders anything) will disrupt the line numbers
After
> Fix empty span line number bug

- readme.txt
- src/block.json
- src/editor/Edit.tsx
- src/editor/controls/Sidebar.tsx
- src/hooks/useDefaults.ts
- src/index.tsx
- src/state/settings.ts
- src/state/theme.ts
- src/types.ts
This allows you to set a tab size to use when editing. It's set per block so eventually there can be "language profiles" that respect common tab widths when editing.
> Add tab size setting

- code-block-pro.php
- readme.txt
- Feature: Added a second copy button to choose from
- Feature: Added a tab size setting for when using the editor to add code. Defaults to 2 spaces.
- Tweak: Adjusts the highlight offset for comic mono
> Release 1.21.0

- readme.txt
- src/front/front.js
- src/front/style.css
Currently if using tabs with line numbers, the first tab is truncated by the line number. This fixes that. Will follow up with a PR to add tab specific features like width, etc
I also added some other line styling fixes, including highlighter length and blur pointer events. See the changelog for details
> Add better support for tabs

- readme.txt
- src/editor/transforms.ts
- src/index.tsx
This adds support for converting a code block pro block back into a standard core code block.
closes #211
> Add support to transform to core code block

- readme.txt
- src/block.json
- src/editor/Edit.tsx
- src/editor/controls/Sidebar.tsx
- src/front/BlockOutput.tsx
- src/hooks/useDefaults.ts
- src/index.tsx
- src/state/theme.ts
- src/types.ts
This adds editor support for inserting tabs. The tab width set in the tab size setting will define the tab width in the editor and the front end
> Add editor support for tabs

- code-block-pro.php
- readme.txt
- Feature: Added tab support in the editor, with spacing options
- Feature: Added a way to convert back into a core code block
- Feature: Added the Non-Ligature version of Jetbrains Mono
- Fix: Fixed a spacing issue with tabs + line numbers
- Fix: Fixed a bug where the line highlighter would calc the longest highlighted line rather than longest line
- Tweak: Added pointer-events none to line blurs that are not removed on hover
> Release 1.22.0

- src/editor/components/ThemeSelect.tsx
This adds the tabsize value to the sidebar theme previews, so they match the editor
> Add tabsize to theme preview

- readme.txt
- src/editor/Edit.tsx
- src/editor/components/buttons/copy/CopyButton.tsx
- src/editor/controls/Sidebar.tsx
- src/front/front.js
This improves encoding/decoding on some sequences, like `G%|X~!"` that would break the decoder. 
In summary, the change will not _not_ encode if saving into the database except for the data attribute. 
closes #222
> Improve decoding on some sequences

- readme.txt
- src/editor/transforms.ts
This fixes a bug where converting the core code block would not properly escape some html items
closes https://github.com/KevinBatdorf/code-block-pro/issues/225
> Fix core code block conversion

- code-block-pro.php
- readme.txt
- src/editor/Edit.tsx
- Fix: Theme previews now respect the tabSize setting
- Fix: Added escapeHTML wrapper on code to code pro transform function
- Fix: Added some clarify on encoding, and added better edge cases handling
- Fix: Fixed an issue with the decoding with some sequences that would cause a block invalidation error.
> Release 1.22.1

- cypress/e2e/styling.cy.js
- src/editor/Edit.tsx
- src/editor/editor.css
- src/front/BlockOutput.tsx
- src/index.tsx
- src/types.ts
- src/util/fonts.ts
This updates how the line number are computed, using a simple formula (`fontSize` * `highestLineNumber` * `0.6` ratio) to estimate a "good enough" width.
Previously it would get the exact width, which fails when two users using differing zoom levels edit a post. Regardless, as was pointed out to me, it shouldn't be reliant on the font size of the user editing it, but the font size of the browser (and user viewing the page).
> WIP: calculate line number width using static values

- .github/workflows/build-production-zip.yml
- .prettierrc.js
- code-block-pro.php
- cypress/e2e/permissions.cy.js
- php/routes.php
- src/Editor.tsx
- src/editor/Edit.tsx
- src/editor/components/misc/MissingPermissions.tsx
- src/editor/controls/Sidebar.tsx
- src/editor/controls/Toolbar.tsx
- src/hooks/useCanEditHTML.ts
- src/index.tsx
- src/types.ts
- src/util/languages.ts
This updates how the unfiltered html cap is checked, hopefully resolving odd conflicts some users have been reporting. 
Includes a component refactor to allow the react hook
User reports:
https://github.com/KevinBatdorf/code-block-pro/issues/235
https://wordpress.org/support/topic/unfiltered_html-issue/
> Update how unfiltered html is checked

- code-block-pro.php
- readme.txt
- Tweak: Line numbers width is now calculated based on the longest line number * font width
- Compatibility: Checks whether the user has permission via the browser instead of passing it in from the server (other plugins were intercepting this check)
> Release 1.24.1

- code-block-pro.php
- readme.txt
- src/editor/Edit.tsx
- src/editor/components/SlotFactory.tsx
- src/editor/controls/Sidebar.tsx
- src/util/code.ts
This adds three sections to the sidebar (just to give a choice for placement) and exposes functionality for anyone to write a plugin.
If you want more functionality exposed, open an issue.
Related conversation: https://github.com/KevinBatdorf/code-block-pro/pull/252#issuecomment-1773092633
Example code for writing a plugin (comment there if you need clarification): https://gist.github.com/KevinBatdorf/de687d5e620dfe2af7645b35b917cd87
> Add pluggable sidebar slots

- readme.txt
- src/front/front.js
This lets you override the text about to be copied, and also lets you fire a callback after the copy takes place (in case you wanted a custom notification)
```js
window.cbpCopyOverride = (code, button) => {
console.log('copied!', button, code)
return `${code}\ntest test test`;
};
window.cbpCopyCallback = (code, button) => {
console.log('callback', button, code)
}
```
> Allow copy override and callback

- readme.txt
- src/front/style.css
This prevents some mobile browsers like Safari from increasing the font size on some strings
Closes https://github.com/KevinBatdorf/code-block-pro/issues/273
> Prevent mobile font adjustments

- cypress/e2e/buttons.cy.js
- readme.txt
- src/block.json
- src/editor/components/FooterSelect.tsx
- src/editor/components/HeaderSelect.tsx
- src/editor/components/buttons/copy/CopyButton.tsx
- src/editor/components/buttons/copy/TextSimple.tsx
- src/editor/components/buttons/sidebar/CopyBtnSettings.tsx
- src/front/front.js
- src/front/style.css
- src/hooks/useDefaults.ts
- src/index.tsx
- src/state/theme.ts
- src/types.ts
Adds a copy button with some customizable test
The color scheme uses parts of the theme
I'll probably only keep this design, but if anyone wants instructions on how to override it to match another design just ping me (maybe open an issue or discussion here) and I'll help out
> Add copy button with text

- cypress/e2e/language.cy.js
- readme.txt
- src/hooks/useTheme.ts
Fixes a bug where plaintext language would error out. I thnk this is because the highlighter on the pro version and this one differ slightly
Closes https://github.com/KevinBatdorf/code-block-pro/issues/283
Related: https://wordpress.org/support/topic/theme-dark-plus-not-found-please-select-a-different-theme
> Fix bug where plaintext crashes editor

- code-block-pro.php
- readme.txt
- Tweak: Changed the saved languages history from 3 to 5
- Fix: Addressed some contrast issues with print styles
- Testing: Updated tests to work better with latest WP
> Release 1.26.2

- readme.txt
- src/util/languages.ts
Fixes the missing ERB template syntax
> Fix erb language

- code-block-pro.php
- readme.txt
Missed updating the readme on the last tag and I worry there are some security plugins that would make noise if I removed or updated the tag, so I think best to just make a patch release with the version update.
> Release 1.26.4

- code-block-pro.php
- package-lock.json
- package.json
- readme.txt
- webpack.config.js
Fixes an issue where webpack plugin from wp was adding rtl styles
closes https://github.com/KevinBatdorf/code-block-pro/issues/339
> Release 1.26.6

- readme.txt
- src/editor/controls/Toolbar.tsx
Hello, I see the button is squeezed in the editor
So I make a pr to fix this.
> fix: set toolbar button width auto

- readme.txt
- src/front/front.js
Moves the scroll position closer to the block when collapsing the height. It checks the line that was set as the max height and centers that.
Here's an example both with and without height animation enabled
https://github.com/user-attachments/assets/19fd68bc-bb5a-43fa-9af3-75a6e2e65546
> Move scroll to block position on collapse

- code-block-pro.php
- readme.txt
- Now scrolls back into view after a max height collapse
- Disables scroll while the container is expanding
- Fixes a bug where collapsing doesn't account for headers
> Release 1.27.1

- cypress/e2e/buttons.cy.js
- cypress/e2e/extra-settings.cy.js
- cypress/e2e/footers.cy.js
- cypress/e2e/headers.cy.js
- cypress/e2e/height.cy.js
- cypress/e2e/language.cy.js
- cypress/e2e/lines.cy.js
- cypress/e2e/misc.cy.js
- cypress/e2e/padding.cy.js
- cypress/e2e/rtl.cy.js
- cypress/e2e/styling.cy.js
- cypress/e2e/themes.cy.js
- cypress/support/features/code.js
- readme.txt
- src/block.json
- src/editor/components/buttons/copy/CopyButton.tsx
- src/editor/components/buttons/sidebar/CopyBtnSettings.tsx
- src/front/front.js
- src/front/style.css
- src/hooks/useDefaults.ts
- src/index.tsx
- src/state/theme.ts
- src/types.ts
This fixes an issue when an html dom parser is used to minify or process the code on the server. It strips out the new lines. 
If you don't want this for some reason (an aggressive theme style maybe), then you'll have to disable it under Buttons
closes https://github.com/KevinBatdorf/code-block-pro/issues/345
closes https://github.com/KevinBatdorf/code-block-pro/issues/249
closes https://github.com/KevinBatdorf/code-block-pro/issues/300
(sorry for the delay)
> Move copy code to textarea

- code-block-pro.php
- readme.txt
- Refactors the copy button to use a textarea for copying
- Removed the WP outline style on the copy button and pre (now only when tab focused)
> Release 1.27.2

- cypress/e2e/extra-settings.cy.js
- cypress/e2e/height.cy.js
- cypress/e2e/misc.cy.js
- cypress/e2e/padding.cy.js
- cypress/e2e/themes.cy.js
- php/compatibility.php
- readme.txt
- src/editor/components/buttons/copy/CopyButton.tsx
- src/front/style.css
- src/index.tsx
- src/util/errors.ts
This wraps the copy code in a `pre` tag to prevent wordpress from running wptexturize on the code.
See here: https://github.com/KevinBatdorf/code-block-pro/issues/367#issuecomment-2984082251
> Prevent wp_texturize from changing copy code

- code-block-pro.php
- readme.txt
= 1.27.4 - 2025-06-20 =
- Prevents wp_texturize from affecting copied code snippets. You will see a block update for this change as I had to wrap the code in a pre tag.
> Release 1.27.4

- code-block-pro.php
- cypress/e2e/buttons.cy.js
- cypress/e2e/extra-settings.cy.js
- readme.txt
- src/editor/components/buttons/copy/CopyButton.tsx
- src/hooks/useDefaults.ts
- src/index.tsx
Fixes an issue where shortcodes are rendering in the copy button
closes https://github.com/KevinBatdorf/code-block-pro/issues/379
> Handle shortcodes in copy button

- code-block-pro.php
- cypress/e2e/buttons.cy.js
- cypress/e2e/extra-settings.cy.js
- readme.txt
- src/util/code.ts
Fixes a bug where shortcodes with attributes would still be rendering.
Reference: https://wordpress.org/support/topic/serious-some-codes-are-read-by-the-system-and-become-critical-errors
> Properly escape shortcodes with attributes
