KevinBatdorf/code-block-pro

readme.txt
src/editor/components/BlockFilter.tsx
src/front/style.css
src/icons.tsx
src/index.tsx

This lets you convert from a code block into the "code pro" block.

Add convert from code block

---

readme.txt
src/editor/components/BlockFilter.tsx
src/util/languages.ts

Lets users convert from https://wordpress.org/plugins/syntaxhighlighter/

Add convert from sytx evolved

---

code-block-pro.php
readme.txt

A patch release to keep pre elements from looking off on some positioning strategies when margins are applied.

Release 1.2.2

---

code-block-pro.php
readme.txt
src/block.json

This is a fix to remove the center/left/right alignment options as it messes with the layout.

Release 1.2.4

---

code-block-pro.php
readme.txt
src/front/style.css

Adds forced pre styles to override some themes

Release 1.2.5

---

code-block-pro.php
readme.txt
src/front/style.css

Adds overrides to support bootstrap based themes

Add bs support

---

code-block-pro.php
readme.txt

- Fix: Add style overrides for the Hueman theme (and generally good overrides)

Release 1.2.7

---

readme.txt
src/front/style.css

The editor styles were mixing with the front end styles causing a weird experience when the line wrapped

Add fix for overflow

---

readme.txt
src/editor/Edit.tsx
src/editor/components/FontSelect.tsx
src/editor/controls/Sidebar.tsx
src/front/style.css
src/index.tsx

Similar to #30 this lets users adjust the line height

Add font line height contols

---

cypress/support/commands.js
readme.txt
src/editor/components/ThemePreview.tsx
src/editor/controls/Sidebar.tsx
src/state/language.ts

This adds a little helper to make it easy to switch between common languages

Add recently used feature

---

readme.txt
src/editor/components/ThemePreview.tsx
src/editor/components/ThemeSelect.tsx
src/editor/editor.css

This could probably pass in the attributes instead of each parts

Show font styling in theme preview

---

code-block-pro.php
readme.txt

- Feature: Add toggle so users can clamp font sizes to reasonable values.
- Show font styling in theme select sidebar

Release 1.5.0

---

code-block-pro.php
readme.txt
src/editor/components/HeaderSelect.tsx
src/hooks/useDefaults.ts

- Fix: Fixes a bug where the header type set to none doesn't persist

Release 1.5.1

---

code-block-pro.php
readme.txt

I should write an automation for this
- Feature: Add additional header styles
- Feature: Allow overriding the label in the header
- Tweak: Adjust copy button opacity interactions

Release 1.6.0

---

code-block-pro.php
readme.txt
src/front/style.css

- Feature: Add line number support

Release 1.7.0

---

src/editor/components/ThemePreview.tsx

This fixes an issue where the theme "Loading..." screen was only rendering at half width.

Fix loading layout issue

---

src/editor/Edit.tsx
src/editor/editor.css
src/front/style.css

Closes https://github.com/KevinBatdorf/code-block-pro/issues/58

Remove padding from right of pre

---

code-block-pro.php
readme.txt
src/front/front.js

I had the var setter after the function that computes the width so it just never got a tru value. This fixes that!

Fix resize bug

---

code-block-pro.php
readme.txt

- Feature: Add footer with left aligned text
- Tweak: Load scripts (copy button, highlight) on multiple lifecycle points
- Tweak: Make the above scripts idempotent so they can run multiple times safely
- Fix: Removes inner focus outline from Gutenberg update

Release 1.10.0

---

code-block-pro.php
readme.txt

- Feature: Add theme name text search
- Feature: Add theme visibility manager to limit visible themes
- Tweak: Show better error when theme is missing
- Fix: Renderer source url has a double slash

Release 1.11.0

---

code-block-pro.php
readme.txt
src/editor/Edit.tsx
src/front/front.js
src/hooks/useTheme.ts

- Fix: Update shiki renderer wasm loader to use ArrayBuffer

Release 1.11.2

---

code-block-pro.php
readme.txt
src/editor/components/ThemePreview.tsx
src/editor/components/ThemeSelect.tsx
src/editor/editor.css
src/hooks/useTheme.ts

- Feature: Added Ara, Power Query, and DAX language support
- Fix: Fixed preview output on theme selection
- Fix: Fixed theme selection font rendering (to match preview better)

Release 1.12.0

---

src/editor/components/SeeMoreSelect.tsx
src/editor/components/seemore/BlockLeft.tsx
src/editor/components/seemore/BlockRight.tsx
src/editor/components/seemore/RoundCenter.tsx
src/front/front.js

I noticed a shift with content below the editor

Tweak padding an button role

---

package-lock.json
package.json
src/editor/controls/Toolbar.tsx

This PR adds the theme name and the two main colors to the toolbar. If pressed, it will open the sidebar.

Add theme info to toolbar

---

.github/workflows/cypress-main.yml
.github/workflows/cypress-push.yml

This runs the wp dev workflow on the main branch only

Run wp dev on main only

---

cypress/e2e/footers.cy.js
src/editor/controls/Toolbar.tsx
src/front/BlockOutput.tsx
src/hooks/useDefaults.ts
src/index.tsx
src/state/theme.ts

This adds filters for adding extra attributes to the editor and frontend output.

Add filters for adding attributes

---

src/hooks/useDefaults.ts

It's not super necessary and tests were more fickle because of it

Remove ready check in defaults

---

cypress/e2e/copy-button.cy.js
cypress/support/e2e.js
package-lock.json
package.json
src/front/front.js

This adds the keydown events for the copy button on the front end
Closes https://github.com/KevinBatdorf/code-block-pro/issues/143

Add space and enter copy events

---

.github/workflows/cypress-main.yml
.github/workflows/cypress-push.yml

This will fetch the latest WP branch and use that for testing on `main`

Fetch wp version in workflow test

---

package.json
src/editor/components/ThemeFilter.tsx
webpack.config.js

This adds a hook next to the "manage themes" button so more buttons can be added
I also added HMR to this PR

Add themes button hook filter

---

code-block-pro.php
readme.txt

- Feature: Added theme identifier to toolbar
- Feature: Added some filters for attributes and buttons
- Tweak: Updated various styles
- Testing: Updated Cypress to test against latest RC on main push
- Testing: Integration tests now run concurrently to isolate flakey failures
- Fix: Added custom endpoint for settings, allowing edit_post cap users
- Fix: Removed a type conversion to false, causing dirty posts on focus
- Accessibility: Added keydown events to frontend copy button

Release 1.14.0

---

code-block-pro.php
readme.txt

- Feature: Add notice to users who do not have permission to update
- Feature: Added hooks to allow users to add their own themes (or via the theme pack)
- Feature: Add plaintext option to allow rendering as text

Release 1.15.0

---

src/editor/components/footers/SimpleStringEnd.tsx
src/editor/components/footers/SimpleStringStart.tsx
src/editor/components/headers/SimpleString.tsx
src/editor/components/seemore/BlockLeft.tsx
src/editor/components/seemore/BlockRight.tsx
src/editor/components/seemore/RoundCenter.tsx
src/util/colors.ts

This fixes the colors on the max height buttons and some of the footers. The trick is to handle css variables properly.

Fix height patterns with custom themes

---

code-block-pro.php
readme.txt

- Feature: Added new language grammars: GD Script, GD Resource, GD Shader, GLSL, Http, Jison, JSON5, Kusto (kql), Protocol Buffers (.proto), Windows Registry (.reg), V, WGSL, and Wolfram
- Tweak: Removed toolbar language select and added functionality to focus on the sidebar setting
- Refactor: Moved header/footer settings out of the language select into their own panels

Release 1.16.0

---

cypress/e2e/lines.cy.js
readme.txt
src/block.json
src/editor/Edit.tsx
src/editor/controls/BlurControl.tsx
src/editor/controls/HighlightingControl.tsx
src/editor/controls/Sidebar.tsx
src/editor/editor.css
src/front/BlockOutput.tsx
src/front/front.js
src/front/style.css
src/hooks/useDefaults.ts
src/index.tsx
src/state/theme.ts
src/types.ts

This PR adds line highlighting on hover
https://user-images.githubusercontent.com/1478421/236598940-a5dc556c-a3b9-45fb-a003-fac7afb242c9.mov
Also with blurring
https://user-images.githubusercontent.com/1478421/236598959-26d4a42a-6141-4d67-910d-d88542b5ec29.mov

Add line highlighting on hover

---

code-block-pro.php
readme.txt

- Feature: Add line highlighting on hover
- Tweak: Updated the line highlighting sidebar language to be more clear (hopefully)
- Fix: Removed pointer events from line highlights so you can select text under it
- Fix: Adds styling to avoid CLS in the editor on page load

Release 1.17.0

---

code-block-pro.php
readme.txt
src/editor/components/ButtonsPanel.tsx
src/editor/components/buttons/ButtonList.tsx
src/hooks/useDefaults.ts
src/index.tsx
src/state/theme.ts
src/types.ts

- Feature: Adds option to output html entities
- Tweak: Creates a new button settings area to support more buttons (coming soon)
- Tweak: Changes copying class to cbp-copying
- Fix: Fixed a bug where default settings weren't saving

Release 1.18.0

---

readme.txt
src/editor/Edit.tsx

Adds an eslint comment to allow the autoFocus prop

Add eslint exception comment

---

code-block-pro.php
readme.txt

= 1.20.0 - 2023-06-25 =
- Feature: Added the following languages: Ledger (Beancount), Cypher (cql), Glimmer js/ts, JSONL, Narrat (nar), Nextflow (nf), Vyper (vy)
- Fix: Fixes an issue in the editor where some languages output an empty span tag that breaks the line number flow.

Release 1.20.0

---

src/editor/components/ButtonsPanel.tsx
src/editor/components/buttons/sidebar/CopyBtnSettings.tsx

This just refactors the button settings area a bit. No user facing changes.

Refactor buttons setting area

---

cypress/e2e/themes.cy.js
cypress/support/commands.js
cypress/support/e2e.js
cypress/support/features/theme.js
cypress/support/helpers.js

This test kept failing on WP next, so this should fix it

Remove observer mock

---

src/types.ts

This just fixes a typescript error

Set footer type to optional

---

readme.txt
src/editor/Edit.tsx
src/editor/controls/Sidebar.tsx
src/front/front.js

This adds better handling with regard to encoding using `encodeURIComponent` when the user opts in to it.

Add fallback approach to opt-in uri encoding

---

readme.txt
src/editor/components/HeightPanel.tsx
src/editor/components/ThemesPanel.tsx
src/editor/components/buttons/sidebar/CopyBtnSettings.tsx
src/editor/controls/Sidebar.tsx
src/hooks/useDefaults.ts
src/state/theme.ts

This PR adds functionality to remember the last choices for the see more button, including theme, transition, and text.

Persist see more button options

---

code-block-pro.php
readme.txt

- Feature: Added Imba and Console syntaxes
- Feature: Added two new header designs based on user requests, both using text inputs
- Tweak: The "see more" button options persist (theme, text, transition only)

Release 1.23.0

---

readme.txt

Add demo links

---

code-block-pro.php
readme.txt

= 1.24.0 - 2023-09-02 =
- Feature: Added Zig, mdc, Mojo, shellsession (console output), and splunk grammars
- Tweak: Combine code aliases

Release 1.24.0

---

code-block-pro.php
readme.txt
src/editor/controls/Sidebar.tsx

- Feature: Allow for overriding copy button text and invoke a callback
- Feature: Added new programming fonts, Monaspace (5), Geist, Cozette and Deja Vu
- Feature: Add pluggable sidebar slots to allow others to add functionality
- Tweak: Reorganized sidebar based on common daily usage
- Legal: Added (open source) license files for all fonts

Release 1.25.0

---

code-block-pro.php
readme.txt

- Feature: Added a copy button that allows for text inputs
- Feature: Added Roboto Mono font (https://fonts.google.com/specimen/Roboto+Mono)
- Feature: Added Hack font (https://github.com/source-foundry/Hack)
- Fix: Added a css dec to stop long text font upsizing on some mobile devices

Release 1.26.0

---

code-block-pro.php
readme.txt

= 1.26.1 - 2024-01-31 =
- Fix: Fixes a bug where the plaintext language would crash the theme render

Release 1.26.1

---

src/front/style.css

Adds a few basic print styles
See here: https://wordpress.org/support/topic/print-view-3/

Add basic print styles

---

.distignore

Closes https://github.com/KevinBatdorf/code-block-pro/issues/350

Add gitignore to distignore

---

code-block-pro.php
cypress/e2e/rtl.cy.js
cypress/support/commands.js
cypress/support/e2e.js
cypress/support/wp-cli.js
package.json
readme.txt
webpack.config.js

Fixes a bug where the rtl stylesheet landed in the build

add rtl fix

---

src/front/style.css

This makes the blur slightly more readable. 
I've been seeing blur like this becoming more common and other implimentations make the code a bit more readable, which I agree is a better approach

Make blur slightly more readable

---

cypress/e2e/height.cy.js
src/block.json
src/editor/components/HeightPanel.tsx
src/editor/components/ThemeFilter.tsx
src/editor/components/ThemeSelect.tsx
src/editor/components/seemore/BlockLeft.tsx
src/editor/components/seemore/BlockRight.tsx
src/editor/components/seemore/RoundCenter.tsx
src/front/front.js
src/hooks/useDefaults.ts
src/index.tsx
src/state/theme.ts
src/types.ts

This adds the option to let user collapse the max-height after expanding it.
https://github.com/user-attachments/assets/8ec29454-6b9a-4ff5-949c-05f1d56b7ae7

Add collapse button support

---

code-block-pro.php
readme.txt

= 1.27.0 - 2025-05-11 =
- Adds support for collapsing code blocks after expanding
- Tweaks the blur effect for better readability
- Fixes a bug where the controls were overflowing the toolbar

Release 1.27.0
